---
- name: Include OS-specific variables
  tags: btrfsmaintenance
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_os_family | lower }}.yml"
      skip: true

- import_tasks: install.yml
  tags: btrfsmaintenance

- import_tasks: configure.yml
  tags: btrfsmaintenance
