---
- name: Prepare ArchLinux Distributions
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: Ensure Python is installed
      raw: pacman -Sy --noconfirm python

- name: Prepare Debian Distributions
  hosts: debian
  gather_facts: false
  tasks:
    - name: Update package cache
      raw: apt-get update
    - name: Ensure Python is installed
      raw: apt-get install -y python3

